# Generated by Django 4.0.2 on 2022-02-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('isbn', models.CharField(max_length=255)),
                ('sub_title', models.TextField()),
                ('published', models.PositiveSmallIntegerField(default=2020)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('link', models.CharField(max_length=255)),
                ('image_link', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='books', to='book.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.publisher')),
            ],
        ),
    ]
