# Generated by Django 3.2.12 on 2022-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
