# Generated by Django 3.2.12 on 2022-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_extrainfo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
