# Generated by Django 3.2.12 on 2022-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority_zarinpal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_if_zarinpal',
            field=models.CharField(default='', max_length=255),
        ),
    ]
