# Generated by Django 3.2.12 on 2022-02-15 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220215_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expire_token',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 18, 14, 48, 559748, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
