# Generated by Django 3.2.12 on 2022-02-16 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220215_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='expire_token',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 6, 33, 32, 831759, tzinfo=utc)),
        ),
    ]
